tests/selenium/test_vote.py, vote/app.py
=> change vote b to dogs

result/views/index.html, tests/selenium/test_result.py
=> update cats to squirrels for result

tests/selenium/test_vote.py, vote/app.py
=> update vote from dogs to cats

result/views/index.html, tests/selenium/test_result.py
=> update result microservice to heroes vs monsters

result/views/index.html, tests/selenium/test_result.py
=> update heroes v dragons

result/views/index.html, tests/selenium/test_result.py
=> update to heroes v dragons

result/views/index.html, tests/selenium/test_result.py
=> update heroes v villains

result/views/index.html, tests/selenium/test_result.py
=> update heroes v pirates

result/views/index.html, tests/selenium/test_result.py
=> updating to heroes v monsters

result/views/index.html, tests/selenium/test_result.py
=> updating heroes v zombies

result/views/index.html, tests/selenium/test_result.py
=> updating heroes v vampires

result/Dockerfile
Fix restarts found by metrics analysis
=> fix restarts of result

result/views/index.html, tests/selenium/test_result.py
=> updating heroes v werewolves

result/views/index.html, tests/selenium/test_result.py
=> updating heroes v dungeons

result/Dockerfile
=> breaking change for demo

result/Dockerfile
New PR to patch failing result service
=> fixing issue with result Dockerfile

worker/Dockerfile, worker/Worker.csproj
Testing updates to remove known vulns from worker.
=> Update worker image

result/views/index.html, tests/selenium/test_result.py
Making change to result after updating dependencies to patch vulnerabilities
=> update result app

result/views/index.html
=> change result

result/views/index.html
=> result change to orcs

result/views/index.html
=> result change to dragons

result/views/index.html
=> result change to goblins

result/views/index.html
=> result change to villains

result/views/index.html
=> result - change to orcs

environments/development/values.yaml, result/views/index.html
=> modify results
